-- ============================================================
-- NySoa BTP — RESET données métier — VERSION FINALE
-- Couvre toutes les tables de l'application.
-- Les comptes auth.users sont conservés.
-- Exécuter dans Supabase > SQL Editor.
-- ============================================================

DO $$ BEGIN EXECUTE 'TRUNCATE salaires               RESTART IDENTITY CASCADE'; EXCEPTION WHEN OTHERS THEN NULL; END; $$;
DO $$ BEGIN EXECUTE 'TRUNCATE pointage               RESTART IDENTITY CASCADE'; EXCEPTION WHEN OTHERS THEN NULL; END; $$;
DO $$ BEGIN EXECUTE 'TRUNCATE pointage_attendance    RESTART IDENTITY CASCADE'; EXCEPTION WHEN OTHERS THEN NULL; END; $$;
DO $$ BEGIN EXECUTE 'TRUNCATE rapports_chantier      RESTART IDENTITY CASCADE'; EXCEPTION WHEN OTHERS THEN NULL; END; $$;
DO $$ BEGIN EXECUTE 'TRUNCATE controles_inopines     RESTART IDENTITY CASCADE'; EXCEPTION WHEN OTHERS THEN NULL; END; $$;
DO $$ BEGIN EXECUTE 'TRUNCATE gantt_taches           RESTART IDENTITY CASCADE'; EXCEPTION WHEN OTHERS THEN NULL; END; $$;
DO $$ BEGIN EXECUTE 'TRUNCATE validations            RESTART IDENTITY CASCADE'; EXCEPTION WHEN OTHERS THEN NULL; END; $$;
DO $$ BEGIN EXECUTE 'TRUNCATE commandes              RESTART IDENTITY CASCADE'; EXCEPTION WHEN OTHERS THEN NULL; END; $$;
DO $$ BEGIN EXECUTE 'TRUNCATE stocks_chantier        RESTART IDENTITY CASCADE'; EXCEPTION WHEN OTHERS THEN NULL; END; $$;
DO $$ BEGIN EXECUTE 'TRUNCATE logistique             RESTART IDENTITY CASCADE'; EXCEPTION WHEN OTHERS THEN NULL; END; $$;
DO $$ BEGIN EXECUTE 'TRUNCATE materiels              RESTART IDENTITY CASCADE'; EXCEPTION WHEN OTHERS THEN NULL; END; $$;
DO $$ BEGIN EXECUTE 'TRUNCATE catalogue_prix         RESTART IDENTITY CASCADE'; EXCEPTION WHEN OTHERS THEN NULL; END; $$;
DO $$ BEGIN EXECUTE 'TRUNCATE photos                 RESTART IDENTITY CASCADE'; EXCEPTION WHEN OTHERS THEN NULL; END; $$;
DO $$ BEGIN EXECUTE 'TRUNCATE journal                RESTART IDENTITY CASCADE'; EXCEPTION WHEN OTHERS THEN NULL; END; $$;
DO $$ BEGIN EXECUTE 'TRUNCATE caisse                 RESTART IDENTITY CASCADE'; EXCEPTION WHEN OTHERS THEN NULL; END; $$;
DO $$ BEGIN EXECUTE 'TRUNCATE budget_felana          RESTART IDENTITY CASCADE'; EXCEPTION WHEN OTHERS THEN NULL; END; $$;
DO $$ BEGIN EXECUTE 'TRUNCATE credits_fournisseurs   RESTART IDENTITY CASCADE'; EXCEPTION WHEN OTHERS THEN NULL; END; $$;
DO $$ BEGIN EXECUTE 'TRUNCATE antoka                 RESTART IDENTITY CASCADE'; EXCEPTION WHEN OTHERS THEN NULL; END; $$;
DO $$ BEGIN EXECUTE 'TRUNCATE contrats               RESTART IDENTITY CASCADE'; EXCEPTION WHEN OTHERS THEN NULL; END; $$;
DO $$ BEGIN EXECUTE 'TRUNCATE devis_lignes           RESTART IDENTITY CASCADE'; EXCEPTION WHEN OTHERS THEN NULL; END; $$;
DO $$ BEGIN EXECUTE 'TRUNCATE devis_lots             RESTART IDENTITY CASCADE'; EXCEPTION WHEN OTHERS THEN NULL; END; $$;
DO $$ BEGIN EXECUTE 'TRUNCATE devis                  RESTART IDENTITY CASCADE'; EXCEPTION WHEN OTHERS THEN NULL; END; $$;
DO $$ BEGIN EXECUTE 'TRUNCATE formations             RESTART IDENTITY CASCADE'; EXCEPTION WHEN OTHERS THEN NULL; END; $$;
DO $$ BEGIN EXECUTE 'TRUNCATE interventions          RESTART IDENTITY CASCADE'; EXCEPTION WHEN OTHERS THEN NULL; END; $$;
DO $$ BEGIN EXECUTE 'TRUNCATE planning_tasks         RESTART IDENTITY CASCADE'; EXCEPTION WHEN OTHERS THEN NULL; END; $$;
DO $$ BEGIN EXECUTE 'TRUNCATE conges                 RESTART IDENTITY CASCADE'; EXCEPTION WHEN OTHERS THEN NULL; END; $$;
DO $$ BEGIN EXECUTE 'TRUNCATE offres_emploi          RESTART IDENTITY CASCADE'; EXCEPTION WHEN OTHERS THEN NULL; END; $$;
DO $$ BEGIN EXECUTE 'TRUNCATE candidatures           RESTART IDENTITY CASCADE'; EXCEPTION WHEN OTHERS THEN NULL; END; $$;
DO $$ BEGIN EXECUTE 'TRUNCATE personnel              RESTART IDENTITY CASCADE'; EXCEPTION WHEN OTHERS THEN NULL; END; $$;
DO $$ BEGIN EXECUTE 'TRUNCATE chantiers              RESTART IDENTITY CASCADE'; EXCEPTION WHEN OTHERS THEN NULL; END; $$;
